### ISSUE TITLE
Leaking memory?

### ISSUE THREAD

**Issue by jameshubbard** [rmagick-temp/rmagick#12]
I've got a script that reorients and resizes pics.  I noticed that when I run it on a directory of files it was consuming all of the system memory.  The directory has 200 images consuming 336MB.  I fixed the problem by using destory! on image variables. After adding these method calls the script uses at most 100MB of memory.  The working script is below.  

My original expectations  were that during each go through the loop that the original image memory would have been freed. In the documentation examples, there wasn't any using the destroy! call. 

Fedora 13
Ruby 1.8.6
RMagick 2.13.1
ImageMagick 6.5.8.10 

```
#!/usr/bin/ruby
require 'RMagick'
include Magick

ARGV.each { |filename|
  origpic = Image::read(filename).first
  newpic = origpic.auto_orient
  origpic.destroy!
  newpic.resize_to_fit!(720)
  newpic.write("lores_"+filename)
  newpic.destroy!
}
```

**Comment by chufarj** [comment]
I was experiencing a huge memory leak.
(Update - it is not a leak!  - read Tim's post about mem allocation and now use GC to take care of memory)

http://rubyforge.org/forum/message.php?msg_id=1995

Rails 2.3.8
RMagick 2.13.1
ImageMagick 6.6.3-10 2010-09-05 Q16
Ruby 1.8.7 (2008-08-11 patchlevel 72) [i586-linux].

when using RMAGICK_ENABLE_MANAGED_MEMORY = true
in In environment.rb (rails)
get a [BUG] Segmentation fault

loop to create 100 images
  create image via composting text, background, crop marks
  save to pdf

print_tab_sheet.write("/app/rails/XXXXXX/public/prints/" + print_file){self.compression=Magick::ZipCompression
   self.page="684x792"
   self.quality=100}

the 'crash' blames a lib routine where I composite...
YYYY_sheet = sheet.composite(YYY, NorthEastGravity, 0, y_off, OverCompositeOp)

---

Workaround instead of RMAGICK_ENABLE_MANAGED_MEMORY
Added GC.start at start (not end) end of each loop 

Performance dropped a bit - will look at removing excessive calls to GC.start,
Otherwise, server is stable now and can generate all the print ready docs I need.

**Comment by rempargo** [comment]
After any image creation in the loop, use this:
`GC.start`

**Comment by mmaiza** [comment]
This is an old thread. It is better to do img.destroy! as GC.start is more expensive.

**Comment by mmaiza** [comment]
Closing this as this is an old issue and there are no memory leaks.
