### ISSUE TITLE
Can't install rmagick on my windows(Ruby192)

### ISSUE THREAD

**Issue by eseosa** [rmagick-temp/rmagick#27]
I always get the error:

"Error installing rmagick:
ERROR: Failed to build gem native extension.

checking for Ruby version >= 1.8.5....yes
checking for stdint.h...**_extconf.rb afiled**_
Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers...."

Can someone  please help me fix this.

**Comment by rmagick-temp** [comment]
Did you make sure that you are using the rmagick-win32 gem. Please read: http://rmagick.rubyforge.org/install-faq.html#win Also I would read the whole page skipping what is not relevant.
If this does not help send me the steps you took till you got the error.

**Comment by eseosa** [comment]
1.Install DevKit : https://github.com/oneclick/rubyinstaller/wiki/Development-Kit .

2.Install ImageMagick 6.6.x with windows installer with headers.
NOTE: 
-Do not install ImageMagick in a path which has spaces in it.
The default path C:/Program Files/... will not work.
Install it at a simpler path.
-- Remove any older installations of ImageMagick and RMagick
3.Set the paths in Environment Variables:

set DFImageMagick environment variable to where ImageMagick is installed
set PATH=%DFImageMagick%;%PATH% (if you don't already have it in PATH)
set CPATH=%DFImageMagick%\include;%CPATH%
set LIBRARY_PATH=%DFImageMagick%\lib;%LIBRARY_PATH%

error :failed to build gem native extension.
checking for ruby version >=1.8.5 ...yes
checking for stdint.h...yes
checking for sys/types.h ...yes
checking for wand/Magickwand.h...no
.....

**Comment by rmagick-temp** [comment]
It seems that it is not finding the ImageMagick header files. When you installed ImageMagick did you make sure that you selected the right options. On you system look for \ImageMagick-6.6.x<some_dir>\include\wand and see if MagickWand.h is there. Also I assume that your path does not have spaces as per instructions and that ImageMagick installed properly. 

Moncef Maiza

**Comment by dw3w4at** [comment]
I had written two entries for installing rmagick on windows with [Development-Kit](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit)
- http://phosphor-escence.blogspot.com/2010/10/install-rmagick-on-mingw-and-msys.html
- http://phosphor-escence.blogspot.com/2010/12/if-you-fail-install-rmagick-on-mingw.html

And I've already pull-requested about this bug in here
https://github.com/rmagick/rmagick/pull/20

**Comment by wingfire** [comment]
Ticket can be closed.
Working with Windows 7 64bit and Ruby 1.9.3.
If the files are not longer available -  at the time you will read this - take the next newer one.
1. Install Ghostscript
   http://downloads.sourceforge.net/project/ghostscript/GPL%20Ghostscript/9.05/gs905w32.exe
2. Install Imagemagick
   Use the 32 bit version, 64bit is not working.
   http://www.imagemagick.org/download/binaries/ImageMagick-6.7.6-1-Q16-windows-dll.exe (2012-03-22)
   Install dev headers (Check!)
   Install into C:\opt\
3. Restart the console/cmd prompt/IDE/.. or just restart windows to make Imagemagick commands available
4. Install rmagick
   gem install rmagick --platform=ruby -- --with-opt-lib=C:/opt/ImageMagick-6.7.6-Q16/lib --with-opt-include=c:/opt/ImageMagick-6.7.6-Q16/include

**Comment by dicom** [comment]
I can confirm that wingfire's recipe works.
Tested on WinXp SP3 32bit & Ruby 1.9.3,p125, using a slightly newer version of ImageMagick than the one listed above.
http://www.imagemagick.org/download/binaries/ImageMagick-6.7.6-2-Q16-windows-dll.exe

**Comment by mrstocks** [comment]
Doesn't work for me, i get a bin/ld.exe: cannot find -lX11

**Comment by casoetan** [comment]
works great. The 64bit versions won't work with rmagic

**Comment by grex22** [comment]
Another confirmation of Wingfire's solution, this one is on Windows Vista SP1, using a ImageMagick 6.5.6-8

**Comment by linduxed** [comment]
Candidate for closing, @mmaiza.

**Comment by SIBUK** [comment]
For all people who are having problems installing rmagick recently I have discovered why we are getting this error message 'ld.exe: cannot find -lX11'. It is because in recent installs of ImageMagick the devs have failed to include an important lib. If you look in your ImageMagick\lib directory you should see 4 files in there. The 3 CORE_RL*.lib files and also a x11.lib file. the x11.lib file is missing from recent versions (in my case version 6.9.0-6).

The solution is simple enough. Uninstall ImageMagick then download an older version from here:
http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/binaries/

In my case I used ImageMagick-6.7.7-0-Q16-windows-dll.exe. Install it and go in to the lib folder and copy the x11.lib file somewhere safe, then uninstall ImageMagick again and re-install whatever new version you want that has the missing file and just copy the file from your safe location in to the ImageMagick lib directory.

Then from your command prompt type:
gem install rmagick --platform=ruby -- --with-opt-lib=C:/ImageMagick/lib --with-opt-include=C:/ImageMagick/include

replacing your imagemagick directory with where-ever you installed it (I heard it doesn't like spaces so I kept  in that directory).

It should then bundle up fine.
