### ISSUE TITLE
error when doing a gem install

### ISSUE THREAD

**Issue by kbdev** [rmagick-temp/rmagick#68]
i continue getting this error when installing this gem. i am trying to install social_stream and i keep getting stuck at this point in the bundle.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

```
    C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb
```

checking for Ruby version >= 1.8.5... yes
checking for stdint.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

**Comment by rmagick-temp** [comment]
You are not providing enough information for me to help you. Something is wrong in path because you seem to want to use ruby 1.9.3 and it is find ruby 1.8.5. This is most likely due to missing or not finding libraries. It seems that you are installing on Windows make sure that CPATH and LIBRARY_PATH are set correctly. 

Moncef

**Comment by kbdev** [comment]
Yep. Definitely saw that a while ago. Lol. I was so mad at myself. 

Ken Bartlett

**Comment by mmaiza** [comment]
Excellent.

**Comment by mmaiza** [comment]
This is resolved so I am closing it.
