### ISSUE TITLE
Wont Install with ImageMagick 6.6.1-5 on OSX 10.6.4

### ISSUE THREAD

**Issue by jacquescrocker** [rmagick-temp/rmagick#9]
RMagick seems to be failing with the latest version of ImageMagick
http://gist.github.com/450815

I installed ImageMagick via the instructions here: http://www.imagemagick.org/www/binary-releases.html (first tried via `brew` but that just about destroyed my mac). ImageMagick seems to be working fine from the commandline, and I have the DYLD_LIBRARY_PATH set propertly as per the instructions. Commands like `convert` work fine.

`gem install rmagick` however still fails.

**Comment by jacquescrocker** [comment]
Here's the full `gem install` results: http://gist.github.com/450824

This is 2.13.1. I'll try from git master and see if that works

**Comment by baror** [comment]
Hello -

It looks like the problem is the library lcms, which ImageMagick thinks is available but is not. You may want to install something that gives you LCMS support or compile ImageMagick with "--without-lcms" (based on the line "ld: library not found for -llcms"). Hopefully, if you fix this, the problem will go away.

I'm yet not sure why RMagick is trying to compile "int t() { InitializeMagick(); return 0; }" .  I'm hoping it's just mkmf's final attempt to compile once the initial compilation fails due to lcms not being around. But, I'll look more into it.

Best,
- Omer.

**Comment by jacquescrocker** [comment]
Thanks for the tip. Looks like I just had a screwed up imagemagick installation. The instructions posted [here](http://www.imagemagick.org/script/binary-releases.php) are quite terrible. As I've learned, setting `DYLD_LIBRARY_PATH` on OSX is a very very bad idea (I still dont know what it does exactly, but setting it will screw up many OSX apps). I guess I should know better than to trust the ImageMagick website's install instructions.

Maybe RMagick can be made a bit more user friendly by checking the dependencies in Ruby and outputting the required ImageMagick installation instructions? But that's a topic for another issue. Closing this one.

RMagick works fine now after removing the `DYLD_LIBRARY_PATH` setting from my ENV, then reinstalling imagemagick view homebrew, and doing `gem install rmagick`. Smooth as butter...
